# Base image
FROM node:16

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY ./app/package*.json /app/

# Install dependencies
RUN npm install

# Copy the project files into the Docker image
COPY ./app /app

# Expose the port the app runs on
EXPOSE 8080

# Command to run the application
CMD ["npm", "run", "serve"]