version: '3.8'
services:
  nginx:
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    # port: 
    #   - "3000:3000"
    container_nmae: client 
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    # port: 
    #   - "5000:5000"
    container_name: backend 
    env_file:
      - ./env/backend.env
  # mongo:
  #   image: "mongo"
  #   container_name: "mongo-db"
