# Frontend Dockerfile
FROM node:16 as build-stage
WORKDIR /app
COPY ./app/package*.json /app/
RUN npm install
COPY ./app /app
RUN npm run build

FROM nginx:stable as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
